name: ROS 2 Jazzy Build CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: osrf/ros:jazzy-desktop
    
    steps:
    - uses: actions/checkout@v4

    - name: Install Build Dependencies
      run: |
        apt-get update
        apt-get install -y python3-colcon-common-extensions python3-rosdep python3-vcstool git
        rosdep update
        # Installe automatiquement toutes les dépendances ROS 2 des paquets du robot
        rosdep install --from-paths ros2_ws/src --ignore-src -y --rosdistro jazzy || true

    - name: Build ROS 2 Workspace
      run: |
        . /opt/ros/jazzy/setup.sh
        cd ros2_ws
        # Compile l'ensemble des paquets de votre robot
        colcon build --symlink-install
